version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432" # Expose PostgreSQL on port 5432
    environment:
      POSTGRES_USER: artychan
      POSTGRES_PASSWORD: Peeeweee12
      POSTGRES_DB: artychan_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always # Automatically restart the container if it stops

volumes:
  postgres_data: